version: '3.8'
services:
  lingva:
    image: lingvatranslate/lingva-translate:latest
    container_name: lingva
    restart: unless-stopped
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
