version: '3'

services:
  lingva:
    container_name: lingva
    image: thedaviddelta/lingva-translate:latest
    restart: unless-stopped
    environment:
      # Změňte na vaši skutečnou doménu
      - site_domain=lingva.ochmann.cz 
      - force_default_theme=light
      - default_source_lang=auto
      - default_target_lang=en
    ports:
      - 3000:3000
